module.exports = {
  semi: true,
  trailingComma: 'es5',
  singleQuote: false,
  printWidth: 100,
  tabWidth: 4,
  bracketSameLine: true,
  plugins: [
    '@ianvs/prettier-plugin-sort-imports',
    'prettier-plugin-tailwindcss',
  ],
  importOrder: [
    '^react',
    '^next',
    '<THIRD_PARTY_MODULES>',
    '^@/types',
    '^@/constants',
    '^@/utils',
    '^@/lib',
    '^@/styles',
    '^@/layouts',
    '^@/contexts',
    '^@/hooks',
    '^@/components',
    '^[./]',
  ],
  importOrderSeparation: true,
  importOrderSortSpecifiers: true,
};
